# NumPy examples

In [1]:
import numpy as np

https://numpy.org/devdocs/user/quickstart.html

## Basics

ndarray.ndim  
the number of axes (dimensions) of the array.

ndarray.shape  
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

ndarray.size  
the total number of elements of the array. This is equal to the product of the elements of shape.

ndarray.dtype  
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

ndarray.itemsize  
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

ndarray.data  
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [6]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [17]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [27]:
c = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
print(c)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [28]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [29]:
# number of axes (dimensions) of the array
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
2


In [30]:
# the dimensions of the array
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(3, 3)


In [31]:
# the total number of elements of the array
print(a.size)
print(b.size)
print(c.size)

3
6
9


In [33]:
# an object describing the type of the elements in the array
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
float64


In [34]:
# the size in bytes of each element of the array
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
4
8


In [35]:
# the buffer containing the actual elements of the array
print(a.data)
print(b.data)
print(c.data)

### Array Creation
np.array  
np.array(sequence, dtype)  

np.zeros  
creates an array full of zeros

np.ones  
creates an array full of ones

np.empty  
creates an array whose initial content is random and depends on the state of the memory

np.arange  
create sequences of numbers

np.linspace  
receives as an argument the number of elements that we want, instead of the step

In [37]:
a = np.array([1, 2, 3])
print(a.dtype)

int32


In [39]:
a = np.array([1, 2, 3], dtype='float64')
print(a.dtype)

float64


In [42]:
a = np.array([1, 2, 3], dtype='int64')
print(a.dtype)

int64


In [43]:
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
a = np.zeros((3, 4), dtype='int')
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [50]:
a = np.ones((2, 3, 4), dtype=np.int16)
print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [53]:
print(a.ndim)
print(a.shape)

3
(2, 3, 4)


In [60]:
a = np.empty((1, 3, 4), dtype=np.int32)
print(a)

[[[65537 65537 65537 65537]
  [65537 65537 65537 65537]
  [65537 65537 65537 65537]]]


In [61]:
a = np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [62]:
a = np.arange(10, 30)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [63]:
a = np.arange(10, 30, 5)
print(a)

[10 15 20 25]


In [64]:
a = np.arange(0, 2, 0.3)
print(a)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [64]:
a = np.arange(0, 2, 0.3)
print(a)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [65]:
a = np.linspace(0, 2, 9)
print(a)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [66]:
a = np.linspace(0, 2, 11)
print(a)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


### Printing arrays

In [79]:
print(np.arange(1100).reshape(11, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [ 800  801  802 ...  897  898  899]
 [ 900  901  902 ...  997  998  999]
 [1000 1001 1002 ... 1097 1098 1099]]


In [77]:
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 1000,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}

In [80]:
np.set_printoptions(threshold=1200)

In [81]:
print(np.arange(1100).reshape(11, 100))

[[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
    14   15   16   17   18   19   20   21   22   23   24   25   26   27
    28   29   30   31   32   33   34   35   36   37   38   39   40   41
    42   43   44   45   46   47   48   49   50   51   52   53   54   55
    56   57   58   59   60   61   62   63   64   65   66   67   68   69
    70   71   72   73   74   75   76   77   78   79   80   81   82   83
    84   85   86   87   88   89   90   91   92   93   94   95   96   97
    98   99]
 [ 100  101  102  103  104  105  106  107  108  109  110  111  112  113
   114  115  116  117  118  119  120  121  122  123  124  125  126  127
   128  129  130  131  132  133  134  135  136  137  138  139  140  141
   142  143  144  145  146  147  148  149  150  151  152  153  154  155
   156  157  158  159  160  161  162  163  164  165  166  167  168  169
   170  171  172  173  174  175  176  177  178  179  180  181  182  183
   184  185  186  187  188  189  190  191  192  193

In [82]:
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 1200,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}

## Shape manipulation

a.ravel()  
returns the array, flattened

.reshape()  
returns the array with a modified shape

.T  
returns the array, transposed

a.resize()  
modifies the array itself

In [85]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [86]:
print(a.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [87]:
print(a.reshape(2, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [88]:
print(a.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [89]:
a.resize((2, 6))
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


np.vstack  

np.hstack

np.column_stack

np.row_stack  
the function row_stack is equivalent to vstack for any input arrays  

np.newaxis  

np.concatenate  

np.r_  

np.c_  

In [91]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [94]:
print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [95]:
print(np.hstack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


In [96]:
# The function column_stack stacks 1D arrays as columns into a 2D array. 
# It is equivalent to hstack only for 2D arrays. 
# For 1D arrays the result is different

print(np.column_stack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


In [97]:
c = np.array([1, 2, 3, 4])
d = np.array([5, 6, 7, 8])

In [98]:
print(np.hstack((c, d)))

[1 2 3 4 5 6 7 8]


In [99]:
print(np.column_stack((c, d)))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [100]:
c[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [102]:
print(np.hstack((c[:, np.newaxis], d[:, np.newaxis])))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [101]:
print(np.column_stack((c[:, np.newaxis], d[:, np.newaxis])))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


np.hsplit

np.vsplit

np.array_split

In [103]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [105]:
# Split `a` into 3
print(np.hsplit(a,2))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [108]:
# Split `a` after the second column
print(np.hsplit(a,(2,)))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [109]:
print(np.vsplit(a,2))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
