Сборник задач по алгебре под редакцией А. И. Кострикина. М.: МЦНМО, 2021.

# Глава 2. Арифметические пространства и линейные уравнения
## §6. Арифметические пространства

**6.1.** Найти линейную комбинацию \\( 3a_1 + 5a_2 - a_3 \\) 

In [11]:
a1 = np.array([4,1,3,-2])
a2 = np.array([1,2,-3,2])
a3 = np.array([16,9,1,-3])
print('Ответ:', tuple(3*a1+5*a2-a3))

Ответ: (1, 4, -7, 7)


**6.2.** Найти вектор x из уравнений:  
а) \\( a_1 + 2a_2 + 3a_3 + 4x = 0 \\)  

Решение: $$ 4x = -(a_1 + 2a_2 + 3a_3) $$  $$ x = -(a_1 + 2a_2 + 3a_3) / 4 $$

In [17]:
a1 = np.array((5, -8, -1, 2))
a2 = np.array((2, -1, 4, -3))
a3 = np.array((-3, 2, -5, 4))
print('Ответ:', tuple(((0 - (a1 + 2 * a2 + 3 * a3)) / 4).astype(int)))

Ответ: (0, 1, 2, -2)


б) \\( 3(a_1 - x) + 2(a_2 + x) = 5(a_3 + x) \\)  
Решение: $$ 3a_1 - 3x + 2a_2 + 2x = 5a_3 + 5x $$  $$ 6x = 3a_1 + 2a_2 - 5a_3 $$ $$ x = (3a_1 + 2a_2 - 5a_3) / 6 $$

In [16]:
a1 = np.array((2, 5, 1, 3))
a2 = np.array((10, 1, 5, 10))
a3 = np.array((4, 1, -1, 1))
print('Ответ:', tuple(((3*a1 + 2 * a2 - 5 * a3) / 6).astype(int)))

Ответ: (1, 2, 3, 4)


**6.3.** Выяснить, являются ли следующие системы векторов линейно независимыми:  
а) \\( a_1 = (1,2,3), a_2 = (3,6,7) \\)  

Решение: 
Если \\( a_1 \\) и \\( a_2 \\) линейно зависимы, то существует &#955;, такая, что  \\( a_1 = \lambda a_2\\). Но 1 / 3 = 2 / 6 &ne; 3 / 7.  
Ответ: Да, линейно независимы

б) \\( a_1 = (4,-2,6), a_2 = (6,-3,9) \\)  

Решение: 
Если \\( a_1 \\) и \\( a_2 \\) линейно зависимы, то существует &#955;, такая, что  \\( a_1 = \lambda a_2\\).  
\\( \lambda = 4 / 6 = -2 / -3 = 6 / 9 = 2 / 3 \\)  
Ответ:  Нет, векторы линейно зависимы

в) \\( a_1 = (2, -3, 1), a_2 = (3, -1, 5) , a_3 = (1, -4, 3)\\) 

In [22]:
A = np.array([[2, -3, 1], 
              [3, -1, 5],
              [1, -4, 3]]
            )
D = int(np.linalg.det(A))
if D == 0: 
    print('Ответ: Нет, векторы линейно зависимы')
else:
    print('Ответ: Да, линейно независимы')

Ответ: Да, линейно независимы


г) \\( a_1 = (5, 4, 3), a_2 = (3, 3, 2) , a_3 = (8, 1, 3)\\) 

In [23]:
A = np.array([[5, 4, 3], 
              [3, 3, 2],
              [8, 1, 3]]
            )
D = int(np.linalg.det(A))
if D == 0: 
    print('Ответ: Нет, векторы линейно зависимы')
else:
    print('Ответ: Да, линейно независимы')

Ответ: Нет, векторы линейно зависимы


д) \\( a_1 = (4, -5, 2, 6), a_2 = (2, -2, 1, 3) , a_3 = (6, -3, 3, 9), a_4 = (4, -1, 5, 6)\\) 

In [24]:
A = np.array([(4, -5, 2, 6), 
              (2, -2, 1, 3), 
              (6, -3, 3, 9), 
              (4, -1, 5, 6)]
            )
D = int(np.linalg.det(A))
if D == 0: 
    print('Ответ: Нет, векторы линейно зависимы')
else:
    print('Ответ: Да, линейно независимы')

Ответ: Нет, векторы линейно зависимы


е) \\( a_1 = (1, 0, 0, 2, 5), a_2 = (0, 1, 0, 3, 4) , a_3 = (0, 0, 1, 4, 7), a_4 = (2, -3, 4, 11, 12)\\)  

Решение: Если векторы линейно зависимы, то существуют числа a, b, c, d, одновременно не равные нулю, такие, что $$ aa_1 + ba_2 + ca_3 + da_4 + a_5 = 0 $$  
Тогда должна быть верна система равенств: $$ a + 0 + 0 + 2d = 0 $$ $$ 0 + b + 0 - 3d = 0 $$ $$ 0 + 0 + c + 4d = 0 $$ $$ 2a + 3b + 4c + 11d = 0 $$ $$ 5a + 4b + 7c + 12d = 0 $$  
Из первых трех равенств a, b и c выражаются через d: $$ a = -2d $$ $$ b = 3d $$ $$ c = -4d $$  
Четвертое равенство принимает вид: \\( -4d + 9d - 16d + 11d = 5d - 5d = 0 \equiv 0 \\)  
Пятое равенство принимает вид:  $$ -10d + 12d - 21d + 12d = 0 $$ $$ -7d = 0 $$ $$ d = 0 $$
Следовательно, все коэффициенты a = b = c = d = 0. Значит, векторы линейно независимы.  
Ответ: Да, линейно независимы.

## §7. Ранг матрицы

In [18]:
import numpy as np

7.1 Найти ранг следующих матриц  
а)

In [4]:
A = np.array([[8, 2, 2, -1, 1],
              [1, 7, 4, -2, 5],
              [-2, 4, 2, -1, 3]
             ])

print('Ответ:', np.linalg.matrix_rank(A))

Ответ: 2


б)

In [19]:
A = np.array([[1, 7, 7, 9],
              [7, 5, 1, -1],
              [4, 2, -1, -3],
              [-1, 1, 3, 5]
             ])

print('Ответ:', np.linalg.matrix_rank(A))

Ответ: 3


в)

In [20]:
A = np.array([[4, 1, 7, -5, 1],
              [0, -7, 1, -3, -5],
              [3, 4, 5, -3, 2],
              [2, 5, 3, -1, 3]
             ])

print('Ответ:', np.linalg.matrix_rank(A))

Ответ: 3


г)

In [21]:
A = np.array([[8, -4, 5, 5, 9],
              [1, -3, -5, 0, -7],
              [7, -5, 1, 4, 1],
              [3, -1, 3, 2, 5]
             ])

print('Ответ:', np.linalg.matrix_rank(A))

Ответ: 3


д)

In [24]:
A = np.array([[-6, 4, 8, -1, 6],
              [-5, 2, 4, 1, 3],
              [7, 2, 4, 1, 3],
              [2, 4, 8, -7, 6],
              [3, 2, 4, -5, 3]
             ])

print('Ответ:', np.linalg.matrix_rank(A))

Ответ: 3


е)

In [25]:
A = np.array([[77, 32, 6, 5, 3],
              [32, 14, 3, 2, 1],
              [6, 3, 1, 0, 0],
              [5, 2, 0, 1, 0],
              [4, 1, 0, 0, 1]
             ])

print('Ответ:', np.linalg.matrix_rank(A))

Ответ: 4


ж) в самом задачнике ответ неправильный ? = 5

In [29]:
A = np.array([[3, 1, 1, 2, -1],
              [0, 2, -1, 1, 2],
              [4, 3, 2, -1, 1],
              [12, 9, 8, -7, 3],
              [-12, -5, -8, 5, 1]
             ])

print('Ответ:', np.linalg.matrix_rank(A))

Ответ: 4


## §8. Системы линейных уравнений

In [3]:
import numpy as np

**8.1.** Найти общее решение и одно частное решение системы линейных уравнений, используя метод Гаусса

**a)** в самом задачнике ответ неправильный

In [60]:
# Создадим матрицу, соответствующую системе уравнений
# Тип float нужен для преобразований
A = np.array([
    [5, 3, 5, 12],
    [2, 2, 3, 5],
    [1, 7, 9, 4]
], dtype=np.float64)

b = np.array([10, 4, 2], dtype=np.float64)

Решение: составим расширенную матрицу `A_ext`.

In [61]:
A_ext = np.column_stack([A, b])
print(A_ext)

[[ 5.  3.  5. 12. 10.]
 [ 2.  2.  3.  5.  4.]
 [ 1.  7.  9.  4.  2.]]


Применим элементарные преобразования к строкам расширенной матрицы A_ext.  
Поменяем местами первую и последнюю строки.

In [62]:
A_ext[0], A_ext[2] = A_ext[2].copy(), A_ext[0].copy()
print(A_ext)

[[ 1.  7.  9.  4.  2.]
 [ 2.  2.  3.  5.  4.]
 [ 5.  3.  5. 12. 10.]]


Теперь применим элементарные преобразования 2 типа (умножение строки на число и прибавление к другой строке)

In [63]:
A_ext[1] = (A_ext[0] / A_ext[0][0]) * (- A_ext[1][0]) + A_ext[1]
A_ext[2] = (A_ext[0] / A_ext[0][0]) * (- A_ext[2][0]) + A_ext[2]
print(A_ext)

[[  1.   7.   9.   4.   2.]
 [  0. -12. -15.  -3.   0.]
 [  0. -32. -40.  -8.   0.]]


In [64]:
A_ext[2] = (A_ext[1] / A_ext[1][1]) * (- A_ext[2][1]) + A_ext[2]
print(A_ext)

[[  1.   7.   9.   4.   2.]
 [  0. -12. -15.  -3.   0.]
 [  0.   0.   0.   0.   0.]]


В системе 4 неизвестных и только 2 главных неизвестных, 2 свободных неизвестных (обозначим \\( x_3 \\) и \\( x_4 \\)).
Найдем остальные члены: $$ 4x_2 + 5x_3 + x_4 = 0 $$ $$ x_2 = (- 5x_3 - x_4) / 4 $$ $$ x_1 + 7x_2 + 9x_3 + 4x_4 = 2 $$ $$ x_1 = (8 - x_3 - 9x_4) / 4 $$

Общее решение: \\( x_2 = (- 5x_3 - x_4) / 4 ; x_1 = (8 - x_3 - 9x_4) / 4 \\)  
Частные решения:

In [73]:
x3 = 0
x4 = 0
x1 = (8 - x3 - 9*x4) / 4
x2 = (-5*x3 - x4) / 4
print((x1, x2, x3, x4))

(2.0, 0.0, 0, 0)


Проверка:

In [74]:
all(A @ np.array([x1, x2, x3, x4]) == b)

True

In [79]:
x3 = -1
x4 = 1
x1 = (8 - x3 - 9*x4) / 4
x2 = (-5*x3 - x4) / 4
print((x1, x2, x3, x4))

(0.0, 1.0, -1, 1)


Проверка:

In [80]:
all(A @ np.array([x1, x2, x3, x4]) == b)

True

**б)**

In [81]:
# Создадим матрицу, соответствующую системе уравнений
# Тип float нужен для преобразований
A = np.array([
    [-9, 6, 7, 10],
    [-6, 4, 2, 3],
    [-3, 2, -11, -15]
], dtype=np.float64)

b = np.array([3, 2, 1], dtype=np.float64)

Решение: составим расширенную матрицу `A_ext`.

In [86]:
A_ext = np.column_stack([A, b])
print(A_ext)

[[ -9.   6.   7.  10.   3.]
 [ -6.   4.   2.   3.   2.]
 [ -3.   2. -11. -15.   1.]]


Применим элементарные преобразования к строкам расширенной матрицы A_ext.  
Поменяем местами первую и последнюю строки.

In [87]:
A_ext[0], A_ext[2] = A_ext[2].copy(), A_ext[0].copy()
print(A_ext)

[[ -3.   2. -11. -15.   1.]
 [ -6.   4.   2.   3.   2.]
 [ -9.   6.   7.  10.   3.]]


Теперь применим элементарные преобразования 2 типа (умножение строки на число и прибавление к другой строке)

In [88]:
A_ext[1] = (A_ext[0] / A_ext[0][0]) * (- A_ext[1][0]) + A_ext[1]
A_ext[2] = (A_ext[0] / A_ext[0][0]) * (- A_ext[2][0]) + A_ext[2]
print(A_ext)

[[ -3.   2. -11. -15.   1.]
 [  0.   0.  24.  33.   0.]
 [  0.   0.  40.  55.   0.]]


In [90]:
# Во торой строке второй элемент тоже равен нулю, берем третий
A_ext[2] = (A_ext[1] / A_ext[1][2]) * (- A_ext[2][2]) + A_ext[2]
print(A_ext)

[[ -3.   2. -11. -15.   1.]
 [  0.   0.  24.  33.   0.]
 [  0.   0.   0.   0.   0.]]


В системе 4 неизвестных и только 2 главных неизвестных, 2 свободных неизвестных (обозначим \\( x_2 \\) и \\( x_4 \\)).

Общее решение: \\( x_3 = \frac{-11x_4}{8} ; x_1 = \frac{2x_2 - 1 + \frac{x_4}{8}}{3} \\)  
Частные решения:

In [99]:
x2 = 6
x4 = 8
x1 = (2*x2 - 1 + x4/8) / 3
x3 = -11 * x4 / 8
print((x1, x2, x3, x4))

(4.0, 6, -11.0, 8)


Проверка:

In [100]:
all(A @ np.array([x1, x2, x3, x4]) == b)

True

In [101]:
x2 = 0
x4 = 0
x1 = (2*x2 - 1 + x4/8) / 3
x3 = -11 * x4 / 8
print((x1, x2, x3, x4))

(-0.3333333333333333, 0, 0.0, 0)


Проверка:

In [102]:
all(A @ np.array([x1, x2, x3, x4]) == b)

True